#! /bin/sh 
cd ~
echo "CONDA INSTALL MODULES"
conda install -c conda-forge pandas matplotlib ipympl ipywidgets jupyterlab-git nb_conda -y
conda install -c conda-forge nodejs
conda install -c conda-forge voila nbresuse -y
conda install -c conda-forge jupyter-lsp python-language-server jupyterlab_code_formatter black -y
conda install -c conda-forge xeus-python=0.8.6 ptvsd -y
echo "INSTALLING LABEXTENSIONS"
jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager -y
jupyter labextension install --no-build jupyterlab-execute-time -y
jupyter labextension install --no-build @jupyter-voila/jupyterlab-preview -y
jupyter labextension install --no-build @krassowski/jupyterlab-lsp -y
jupyter labextension install --no-build @ryantam626/jupyterlab_code_formatter -y
jupyter labextension install --no-build jupyterlab-drawio -y
jupyter labextension install --no-build @krassowski/jupyterlab_go_to_definition -y
jupyter labextension install --no-build @jupyterlab/google-drive -y
jupyter labextension install --no-build @telamonian/theme-darcula -y
jupyter labextension install --no-build @jupyterlab/toc -y
jupyter labextension install --no-build @lckr/jupyterlab_variableinspector -y
#jupyter labextension install --no-build jupyterlab_voyager -y
jupyter labextension install --no-build jupyterlab-topbar-extension -y
jupyter labextension install --no-build jupyterlab-system-monitor -y
jupyter labextension install --no-build jupyterlab-theme-toggle -y
#jupyter labextension install --no-build @jupyterlab/dataregistry-extension -y
jupyter labextension install --no-build @ijmbarr/jupyterlab_spellchecker -y
jupyter labextension install --no-build @jupyterlab/debugger -y
echo "NPM INSTALLING PACKAGES"
echo "bash lps"
npm install --save-dev bash-language-server -y
echo "javascript lps"
npm install --save-dev javascript-typescript-langserver -y
#echo "sql lps"
#npm install --save-dev sql-language-server -y
echo "unified lps"
npm install --save-dev unified-language-server -y
echo "css lps"
npm install --save-dev vscode-css-languageserver-bin -y
echo "html lps"
npm install --save-dev vscode-html-languageserver-bin -y
echo "json lps"
npm install --save-dev vscode-json-languageserver-bin -y
#echo "serverextension enable
#jupyter serverextension enable --py jupyterlab_code_formatter
echo "BUILDING JUPYTER LAB"
jupyter lab build --dev-build=False --minimize=False
sudo systemctl restart jupyter
