#! /bin/sh 
echo $VIRTUAL_ENV
source /opt/jupyterhub/bin/activate
echo $VIRTUAL_ENV
echo "KERNELS"
read -p "Install bash_kernel? [y/N]" bk
if [[ $ == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -q bash_kernel
    sudo /opt/jupyterhub/bin/python3 -m bash_kernel.install
fi
# read -p "Install Javascript? [y/N]" js 
# if [[ $js == "y" ]]; then
#     sudo npm install -g --unsafe-perm ijavascript
#     sudo ijsinstall --install=global
#fi

# read -p "Install Nodejs? [y/N]" nj 
# if [[ $nj == "y" ]]; then
#     source /opt/jupyterhub/bin/activate
#     cd sudo ~
#     sudo git clone https://github.com/notablemind/jupyter-nodejs.git
#     sudo cd jupyter-nodejs
#     sudo mkdir -p ~/.ipython/kernels/nodejs/
#     sudo npm install && sudo node install.js
#     sudo npm run build
#     sudo npm run build-ext
#     sudo jupyter console --kernel nodejs
# fi

echo "EXTENSIONS"
jupyter labextension install --no-build \
    @jupyter-widgets/jupyterlab-manager \
    jupyterlab-execute-time \
    @krassowski/jupyterlab_go_to_definition \
    @jupyterlab/google-drive \
    @jupyterlab/toc \
    @lckr/jupyterlab_variableinspector \
    jupyterlab-topbar-extension jupyterlab-system-monitor jupyterlab-theme-toggle \
    @ijmbarr/jupyterlab_spellchecker

read -p "Install Voila? [y/N]" vv
if [[ $vv == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install voila
    jupyter labextension install --no-build @jupyter-voila/jupyterlab-preview
fi
read -p "Install Language server? [y/N]" ls
if [[ $ls == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install jupyter-lsp 
    jupyter labextension install --no-build @krassowski/jupyterlab-lsp 
    sudo /opt/jupyterhub/bin/python3 -m pip install python-language-server[all]
    read -p  "bash lps"
    sudo npm install --save-dev -y \
        bash-language-server \
        javascript-typescript-langserver \
        unified-language-server \
        vscode-css-languageserver-bin \
        vscode-html-languageserver-bin \
        vscode-json-languageserver-bin
fi
read -p "Install Code Formatter? [y/N]" cf
if [[ $cf == "y" ]]; then
    jupyter labextension install --no-build @ryantam626/jupyterlab_code_formatter black #autopep8 yapf isort
    sudo /opt/jupyterhub/bin/python3 -m pip install jupyterlab-code-formatter
    echo $VIRTUAL_ENV
    jupyter serverextension enable --py jupyterlab_code_formatter
fi
read -p "Install Debugger? [y/N]" db
if [[ $db == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install xeus-python ptvsd
    jupyter labextension install --no-build @jupyterlab/debugger
fi

echo "THEMES"
echo "dracula"
jupyter labextension install --no-build @telamonian/theme-darcula -y

<< COMMENT
read -p "Install ...? [y/N]" 
if [[ $ == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -y 
fi
COMMENT

echo "BUILDING JUPYTER LAB"
jupyter lab build --dev-build=False --minimize=False
echo $VIRTUAL_ENV
source /opt/jupyterhub/bin/dectivate
echo $VIRTUAL_ENV
sudo systemctl restart jupyter