#! /bin/sh 
source /opt/jupyterhub/bin/activate
echo "KERNELS"
read -p "Install bash_kernel? [y/N]" bk
if [[ $ == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -q bash_kernel
    sudo /opt/jupyterhub/bin/python3 -m bash_kernel.install
fi
read -p "Install Javascript? [y/N]" js 
if [[ $js == "y" ]]; then
    sudo npm install -g --unsafe-perm ijavascript
    sudo ijsinstall --install=global
fi
read -p "Install Nodejs? [y/N]" nj 
if [[ $nj == "y" ]]; then
    source /opt/jupyterhub/bin/activate
    cd sudo ~
    sudo git clone https://github.com/notablemind/jupyter-nodejs.git
    sudo cd jupyter-nodejs
    sudo mkdir -p ~/.ipython/kernels/nodejs/
    sudo npm install && sudo node install.js
    sudo npm run build
    sudo npm run build-ext
    sudo jupyter console --kernel nodejs
fi

echo "EXTENSIONS"
read -p "DEBUG jupyterlab-manager"
jupyter labextension install --no-build @jupyter-widgets/jupyterlab-manager
read -p "DEBUG jupyterlab-execute-time"
jupyter labextension install --no-build jupyterlab-execute-time
read -p "DEBUG jupyterlab_go_to_definition"
jupyter labextension install --no-build @krassowski/jupyterlab_go_to_definition
read -p "DEBUG google-drive"
jupyter labextension install --no-build @jupyterlab/google-drive
read -p "DEBUG table of content"
jupyter labextension install --no-build @jupyterlab/toc
read -p "DEBUG variableinspector"
jupyter labextension install --no-build @lckr/jupyterlab_variableinspector
read -p "DEBUG topbar"
jupyter labextension install --no-build jupyterlab-topbar-extension jupyterlab-system-monitor jupyterlab-theme-toggle
read -p "DEBUG spellchecker"
jupyter labextension install --no-build @ijmbarr/jupyterlab_spellchecker




read -p "Install Voila? [y/N]" vv
if [[ $vv == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -y voila
    jupyter labextension install --no-build @jupyter-voila/jupyterlab-preview
fi
read -p "Install Language server? [y/N]" ls
if [[ $ls == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -y jupyter-lsp 
    jupyter labextension install --no-build @krassowski/jupyterlab-lsp 
    sudo /opt/jupyterhub/bin/python3 -m pip install -y python-language-server[all]
    read -p  "bash lps"
    sudo pm install --save-dev bash-language-server -y
    read -p  "javascript lps"
    sudo npm install --save-dev javascript-typescript-langserver -y
    read -p  "unified lps"
    sudo npm install --save-dev unified-language-server -y
    read -p  "css lps"
    sudo npm install --save-dev vscode-css-languageserver-bin -y
    read -p  "html lps"
    sudo npm install --save-dev vscode-html-languageserver-bin -y
    read -p  "json lps"
    sudo npm install --save-dev vscode-json-languageserver-bin -y
    read -p  "sql lps"
    sudo npm install --save-dev sql-language-server -y 
fi
read -p "Install Code Formatter? [y/N]" cf
if [[ $cf == "y" ]]; then
    jupyter labextension install --no-build @ryantam626/jupyterlab_code_formatter
    sudo /opt/jupyterhub/bin/python3 -m pip install -y jupyterlab_code_formatter
    jupyter serverextension enable --py jupyterlab_code_formatter black # autopep8 yapf isort
fi
read -p "Install Debugger? [y/N]" db
if [[ $db == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -y xeus-python ptvsd
    jupyter labextension install --no-build @jupyterlab/debugger
fi

echo "THEMES"
read -p "DEBUG dracula"
jupyter labextension install --no-build @telamonian/theme-darcula -y

<< COMMENT
read -p "Install ...? [y/N]" 
if [[ $ == "y" ]]; then
    sudo /opt/jupyterhub/bin/python3 -m pip install -y 
fi
COMMENT

echo "BUILDING JUPYTER LAB"
jupyter lab build --dev-build=False --minimize=False
source /opt/jupyterhub/bin/dectivate
sudo systemctl restart jupyter