#!/bin/bash
echo "Install packages for SMB"
sudo apt update -qq && sudo apt upgrade -qq
sudo apt install git samba samba-common-bin -qq

echo "set up smb"
if [[ $(grep -Ril "\[home\]" /etc/samba/smb.conf) == "/etc/samba/smb.conf" ]]; then
	echo  "home folder is already set in smb.conf: no changes made"
else
	echo "[home]
	path = ~
	writeable=Yes
	create mask=0777
	directory mask=0777
	public=no" | sudo tee /etc/samba/smb.conf -a
fi
echo "set password for smb"
sudo smbpasswd -a $USER
sudo systemctl restart smbd
echo "smb is set"
