#! /bin/sh
## Installscript for miniconda

# check running sudo
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root, add sudo command"
    exit
fi

# check if app already is installed
if [[ -d /opt/miniconda3 ]]
then
    echo "It seems miniconda3 is alreay installed in /opt. Pleas update from application."
    echo "Skipping download and install"
else
    echo "Installling miniconda"
    # update system and install dependendies
    apt update && apt install wget -y && apt upgrade wget -y
    
    # download miniconda
    cd ~
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    
    # install miniconda
    bash Miniconda3-latest-Linux-x86_64.sh
    echo "Miniconda is geinstalleerd"
    # change owner of /opt/miniconda3 fo user
    chown -R $(logname) /opt/miniconda3
    
    # clean up
    cd ~
    rm Miniconda3-latest-Linux-x86_64.sh
        
fi

# add init to .bashrc
sudo -u $(logname) /opt/miniconda3/bin/conda init

# instalscript is finisched
echo "Sricpt is finished installing Miniconda"
exit