#! /bin/sh
## Script to make syncthing autostart

# check running sudo
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root, add sudo command"
    exit
fi

# check if app already is installed
apt update
if [[ -f /usr/bin/syncthing ]]
then
    echo "It seems Syncthing is alreay installed. Updating."
    apt upgrade syncthing -y
else
    apt install syncthing -y
fi

# update system and install dependendies
apt install wget -y  && apt upgrade wget -y

# make syncthing autostart
# following instructions on https://docs.syncthing.net/users/autostart.html#linux using systemd
echo "setting autostart"
cd /etc/systemd/system
wget https://raw.githubusercontent.com/syncthing/syncthing/v1.6.1/etc/linux-systemd/system/syncthing%40.service
mv syncthing@.service syncthing.service
sudo -u $(logname) sudo systemctl enable syncthing.service
sudo -u $(logname) sudo systemctl start syncthing.service
echo "done"
# end