#! /bin/sh
## Installscript for miniconda

echo "Part 1: Installing Jupyterhub"
echo ">> INSTALLING DEPENDENCIES"
curl -sL https://deb.nodesource.com/setup_current.x | sudo -E bash -
sudo apt update -qq
sudo apt install -qq python3 python3-dev git curl python3-venv nodejs
sudo python3 -m venv /opt/jupyterhub/
sudo /opt/jupyterhub/bin/python3 -m pip install -q wheel
sudo /opt/jupyterhub/bin/python3 -m pip install -q jupyterhub jupyterlab
sudo /opt/jupyterhub/bin/python3 -m pip install -q -r requirements.txt ipywidgets
sudo npm install -g configurable-http-proxy
echo ">> INSTALLING JUPYTERHUB"
sudo mkdir -p /opt/jupyterhub/etc/jupyterhub/
cd /opt/jupyterhub/etc/jupyterhub/
sudo /opt/jupyterhub/bin/jupyterhub --generate-config
sudo sed -i s/"# c.Spawner.default_url = ''"/"c.Spawner.default_url = '\/lab'"/g jupyterhub_config.py

sudo mkdir -p /opt/jupyterhub/etc/systemd
PathJupServ=/opt/jupyterhub/etc/systemd/jupyterhub.service
if [[ $(sudo grep -Ril "\[Unit\]" $PathJupServ) == $PathJupServ ]]; then
    echo "service file exists: no file created"
else
        sudo tee -a $PathJupServ > /dev/null <<EOT
[Unit]
Description=JupyterHub
After=syslog.target network.target

[Service]
User=root
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/jupyterhub/bin"
ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
EOT
fi
sudo ln -s /opt/jupyterhub/etc/systemd/jupyterhub.service /etc/systemd/system/jupyterhub.service
sudo systemctl daemon-reload
sudo systemctl enable jupyterhub.service
#sudo systemctl start jupyterhub.service
#sudo systemctl status jupyterhub.service
#sudo systemctl stop jupyterhub.service

PathJupDesk=/usr/share/applications/jupyterhub.desktop
#cd /opt/jupyterhub
#wget https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
if [[ $(sudo grep -Ril "\[Desktop\ Entry\]" $PathJupDesk) == $PathJupDesk ]]; then
        echo "service file exists: no file created"
else
        sudo tee -a $PathJupDesk > /dev/null << EOT
[Desktop Entry]
Type=Application
Name=Jupyterhub
Exec=systemctl start jupyterhub
Icon=/opt/jupyterhub/share/jupyterhub/static/images/jupyterhub-80.png
User=root
EOT
fi
echo "Jupyterhub is installed"

echo "Part 2: Installing conda for the whole system"
read -p "Install Anaconda of Miniconda? (miniconda is deafault) [anaconda/miniconda] " am
if [[ $(am) != "anaconda" ]]; then
        echo "Installing miniconda3"
        # check if app already is installed
        if [[ -d /opt/conda ]]
        then
                echo "It seems (mini/ana)conda is alreay installed in /opt. Please update from application."
                echo "Skipping download and install"
        else
                echo "Installling miniconda"
                echo "NB choose install location /opt/conda"
                wget -O - https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh | sudo bash
                ls -hal
                echo "Miniconda is geinstalleerd"     
        fi

        conda config --add channels conda-forge

        # instalscript is finisched
        echo "Sricpt is finished installing Miniconda"
else
        curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg
        sudo install -o root -g root -m 644 conda.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" | sudo tee /etc/apt/sources.list.d/conda.list
        rm conda.gpg
        sudo apt update -qq
        sudo apt install conda -qq
        sudo ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
fi

sudo mkdir /opt/conda/envs/
sudo chown -r @USER /opt/conda
/opt/conda/bin/conda init # add init to .bashrc for user
sudo /opt/conda/bin/conda init # add init to .bashrc for root
fi
echo "Conda is installed"

read -p "Do you want to install extensions en languageservers for Jupyterlab? [y/n] " e
if [ $e != "y" ]; then
        echo "Skipping extending Jupyterlab"
else
        source ./Linux-install-scripts/extend_jupyter
        echo "Jupyterlab extended"
fi
