#! /bin/sh
## Install script for code-server

# check running sudo
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root, add sudo command"
    exit
fi

# check if app already is installed
if [[ -d /opt/code-server ]]
then
    echo "It seems code-server is alreay installed. Pleas update from application."
    exit
fi

# update system and install dependendies
apt update && apt install wget -y

## install code-server
# download
cd /opt
wget https://github.com/cdr/code-server/releases/download/3.0.2/code-server-3.0.2-linux-x86_64.tar.gz
# extract binary
tar -xvf code-server-3.0.2-linux-x86_64.tar.gz
# remane folder
mv code-server-3.0.2-linux-x86_64 code-server
# link binary to /usr/bin
ln -s /opt/code-server/code-server /usr/bin/

# create .desktop
cat > /usr/share/applications/code-server.desktop << EOF
[Desktop Entry]
Type=Application
Name=Code-server: start server
Exec=code-server --auth none --disable-telemetry --open
Icon=/opt/code-server/src/browser/media/pwa-icon-96.png
EOF

# clean up
rm code-server-3.0.2-linux-x86_64.tar.gz

# installing is finisched
echo "Done"
exit
