#! /bin/sh
## Installscript for miniconda

# check if app already is installed
if [[ -d /opt/miniconda3 ]]
then
    echo "It seems miniconda3 is alreay installed in /opt. Pleas update from application."
    echo "Skipping download and install"
else
    echo "Installling miniconda"
    # update system and install dependendies
    sudo apt update && sudo apt install wget -y && sudo apt upgrade wget -y
    
    # download miniconda
    cd ~
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    
    # install miniconda
    sudo bash Miniconda3-latest-Linux-x86_64.sh
    echo "Miniconda is geinstalleerd"
    # change owner of /opt/miniconda3 fo user
    sudo chown -R $(logname) /opt/miniconda3
    
    # clean up
    cd ~
    rm Miniconda3-latest-Linux-x86_64.sh
        
fi

# add init to .bashrc
/opt/miniconda3/bin/conda init

# instalscript is finisched
echo "Sricpt is finished installing Miniconda"

echo "Installing miniconda"
cd /opt/miniconda3
wget https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
cd ~
source /opt/miniconda3/bin/activate
conda config --add channels conda-forge

echo "Installing jupyterhub"
conda install jupyterhub notebook -y
jupyterhub --generate-config

PathJupServ=/etc/systemd/system/jupyterhub.service

if [[ $(sudo grep -Ril "\[Unit\]" $PathJupServ) == $PathJupServ ]]; then
    echo "service file exists: no file created"
else
        sudo tee -a $PathJupServ > /dev/null <<EOT
[Unit]
Description=JupyterHub
After=syslog.target network.target

[Service]
User=root
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/miniconda3/bin"
ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/miniconda3/etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
EOT
fi
<< COMMENT

echo "Installing Jupyterlab"
conda install -c conda-forge jupyterlab
jupyter notebook --generate-config
jupyter notebook password

if [[ $(sudo grep -Ril "\[Unit\]" /etc/systemd/system/jupyter.service) == "/etc/systemd/system/jupyter.service" ]]; then
    echo "service file exists: no file created"
else
	sudo tee -a /etc/systemd/system/jupyter.service > /dev/null <<EOT

EOT
fi

#systemctl enable jupyterhub.service
sudo systemctl daemon-reload

if [[ $(sudo grep -Ril "\[Desktop\ Entry\]" /usr/share/applications/jupyterlab.desktop) == "/usr/share/applications/jupyterlab.desktop" ]]; then
        echo "service file exists: no file created"
else
	sudo tee -a /usr/share/applications/jupyterlab.desktop > /dev/null << EOT
[Desktop Entry]
Type=Application
Name=Jupyterlab
Exec=systemctl start jupyter
Icon=/opt/miniconda3/1200px-Jupyter_logo.svg.png
EOT
fi

echo "Installing bash_kernel"
conda install -c conda-forge bash_kernel
python -m bash_kernel.install
COMMENT
cd ~
echo "Jupyterlab is installed"

read -p "Do you want to install extensions en languageservers for Jupyterlab? [y/n] " e
if [ $e != "y" ]; then
        echo "Skipping extending Jupyterlab"
else
        source ./Linux-install-scripts/extend_jupyter
        echo "Jupyterlab extended"
fi
