#! /bin/sh

## Install script for code-server

# update system
sudo apt update && sudo apt upgrade -y

# install dependencies
sudo apt install wget

# download code-server
if [[ -f ~/Apps ]]
then
    echo "<file> exists on your filesystem."
else
    mkdir ~/Apps
fi

cd ~/Apps
wget https://github.com/cdr/code-server/releases/download/3.0.2/code-server-3.0.2-linux-x86_64.tar.gz

# extract binary
tar -xvf code-server-3.0.2-linux-x86_64.tar.gz

# remane folder
mv code-server-3.0.2-linux-x86_64 code-server

# link binary to /usr/bin
sudo ln -s ~/Apps/code-server/code-server /usr/bin/

# create .desktop
cat > /home/simsu/file.txt << ENDOFFILE
[Desktop Entry]
Type=Application
Name=Code-server
Exec=code-server --auth none
Icon=code
ENDOFFILE

# clean up
rm ~/Apps/code-server-3.0.2-linux-x86_64.tar.gz

# installing is finisched
echo "Done"
exit
