#! /bin/sh
# This script should be run after fresh install

cd ~
echo "Starting setup"
sudo apt update -qq
# check which OS is running
OS=$(uname -a)
echo "System: $OS"
if echo "$OS" | grep -q "penguin"
then
	OS="ChromeOS"
	echo "> Setting up Linux for $OS"

	echo ">> Writing list of base-packages to ~/.base-packages"
	sudo apt list --installed > ~/.base-packages
	
	echo ">> Folowing rules should be added for minimal installation packages"	
	if [[ $(sudo grep -Ril "APT::" /etc/apt/apt.conf.d/99_norecommends)  == "/etc/apt/apt.conf.d/99_norecommends" ]]; then
		echo "Rules already in place: no changes made"
	else
		sudo tee -a /etc/apt/apt.conf.d/99_norecommends -a > /dev/null <<EOT
APT::Install-Recommends "false";
APT::AutoRemove::RecommendsImportant "false";
APT::AutoRemove::SuggestsImportant "false";
EOT
		echo "Rules added to /etc/apt/apt.conf.d/99_norecommends"
	fi
	
	echo ">> Installing packages"
	sudo apt --fix-broken install -qq
	sudo apt install git nano mesa-utils debfoster -qq
	
	echo ">> Minimize system with Defoster"
	sudo debfoster -q
	sudo apt install bash-completion -qq
	
	echo ">> Updating system"
	sudo apt dist-upgrade -qq
	sudo apt upgrade -qq

	echo ">> Cleanup"
	sudo apt autoremove --purge -qq
	sudo apt clean -qq
	sudo apt autoclean -qq

	echo "> Base setup DONE"
else
	# add other OS if it becomes applicable
	# Raspberry pi OS, ..., ...
	OS="...other..."
	echo "os is $OS"
fi

echo "Installing packages"
cd ~/Linux-install-scripts
if [ $OS == "ChromeOS" ]
then
	echo "no specific CHromeOS packages added" # add ChromeOS specific packages
else
	read -p "Do you want to install NFS-client? [y/n] " n
	read -p "Do you want to install SMB-server? [y/n] " s
fi
read -p "Do you want to install Jupyterlab? [y/n] " j

if [[ $n == "y" ]]; then
	source ./install_nfs_client
	echo "NFS DONE"
fi
if [[ $s == "y" ]]; then
        source ./install_smb
	echo "SMB DONE"
fi
if [[ $j == "y" ]]; then
        source ./install_jupyter
	echo "JUPYTER DONE"
fi

echo "Setup and installs are DONE. Exitting now."
exit 0
