#! /bin/sh
# This script should be run after fresh install

sudo apt update
# check which OS is running
OS=$(uname -a)
echo "System: $OS"
if echo "$OS" | grep -q "penguin"
then
	OS="ChromeOS"
	echo "Setting up Linux for $OS"

	echo "> Writing list of base-packages to ~/.base-packages"
	sudo apt list --installed > ~/.base-packages
	
	echo "Folowing rules should be added for minimal installation packages"	
	if [[ $(sudo grep -Ril "APT::" /etc/apt/apt.conf.d/99_norecommends)  == "/etc/apt/apt.conf.d/99_norecommends" ]]; then
		echo "Rules already in place: no changes made"
	else
		sudo tee -a /etc/apt/apt.conf.d/99_norecommends -a > /dev/null <<EOT
APT::Install-Recommends "false";
APT::AutoRemove::RecommendsImportant "false";
APT::AutoRemove::SuggestsImportant "false";
EOT
		echo "Rules added to /etc/apt/apt.conf.d/99_norecommends"
	fi
	
	echo "Installing packages"
	sudo apt install git nano mesa-utils debfoster -y
	
	echo "Minimize system with Defoster"
	sudo debfoster -q
	
	echo "Updating system"
	sudo apt dist-upgrade -y
	sudo apt upgrade -y

	echo "Cleanup"
	sudo apt autoremove --purge
	sudo apt clean
	sudo apt autoclean

	echo "Base setup DONE"
else
	# add other OS if it becomes applicable
	# Raspberry pi OS, ..., ...
	OS="other"
	echo "os is $OS"
fi
