#!/bin/bash
echo "Install packages for SMB"
sudo apt update && sudo apt upgrade -y
sudo apt install git samba samba-common-bin -y

echo "set up smb"
echo "[home]
path = ~
writeable=Yes
create mask=0777
directory mask=0777
public=no" >> /etc/samba/smb.conf
echo "set password for smb"
sudo smbpasswd -a pi
sudo systemctl restart smbd
echo "smb is set"
