#!/bin/bash
cho "Installing python, pip and other packages"
sudo apt purge -y python*
sudo apt autoremove -y
sudo apt update && sudo apt upgrade -y
sudo apt install -y python3 python3-pip
sudo pip3 install setuptools
sudo apt install -y libffi-dev
sudo pip3 install cffi
pip3 install jupyterlab
pip3 install voila
echo "[Unit]
Description=Jupyter Lab
[Service]
Type=simple
PIDFile=/run/jupyter.pid
ExecStart=/bin/bash -c "/usr/local/bin/jupyter-lab"
User=$USER
Group=pi
WorkingDirectory=/home/pi
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target" | sudo tee -a /etc/systemd/system/jupyter.service > /dev/null
sudo systemctl enable jupyter.service
sudo systemctl daemon-reload
jupyter notebook --generate-config
jupyter notebook password
echo "Set up https with instructions on https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication"
nano ~/.jupyter/jupyter_notebook_config.py
