#! /bin/sh
## Installscript for miniconda

# check running sudo
<< COMMENT
if [[ $(/usr/bin/id -u) -ne 0 ]]; then
    echo "Not running as root, add sudo command"
    exit
fi
COMMENT

# check if app already is installed
if [[ -d /opt/miniconda3 ]]
then
    echo "It seems miniconda3 is alreay installed in /opt. Pleas update from application."
    echo "Skipping download and install"
else
    echo "Installling miniconda"
    # update system and install dependendies
    sudo apt update && sudo apt install wget -y && sudo apt upgrade wget -y
    
    # download miniconda
    cd ~
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    
    # install miniconda
    sudo bash Miniconda3-latest-Linux-x86_64.sh
    echo "Miniconda is geinstalleerd"
    # change owner of /opt/miniconda3 fo user
    sudo chown -R $(logname) /opt/miniconda3
    
    # clean up
    cd ~
    rm Miniconda3-latest-Linux-x86_64.sh
        
fi

# add init to .bashrc
/opt/miniconda3/bin/conda init

# instalscript is finisched
echo "Sricpt is finished installing Miniconda"

echo "Installing Jupyterlab"
cd /opt/miniconda3
wget https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png
cd ~
source /opt/miniconda3/bin/activate
conda install -c conda-forge jupyterlab
jupyter notebook --generate-config
jupyter notebook password

if [[ $(sudo grep -Ril "\[Unit\]" /etc/systemd/system/jupyter.service) == "/etc/systemd/system/jupyter.service" ]]; then
    echo "service file exists: no file created"
else
	sudo tee -a /etc/systemd/system/jupyter.service > /dev/null <<EOT
[Unit]
Description=Jupyter Lab

[Service]
Type=simple
PIDFile=/run/jupyter.pid
ExecStart=/opt/miniconda3/bin/jupyter-lab
User=$(logname)
Group=$(logname)
WorkingDirectory=~
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOT
fi

#systemctl enable jupyter.service
sudo systemctl daemon-reload

if [[ $(sudo grep -Ril "\[Desktop\ Entry\]" /usr/share/applications/jupyterlab.desktop) == "/usr/share/applications/jupyterlab.desktop" ]]; then
        echo "service file exists: no file created"
else
	tee -a /usr/share/applications/jupyterlab.desktop > /dev/null << EOT
[Desktop Entry]
Type=Application
Name=Jupyterlab
Exec=systemctl start jupyter
Icon=/opt/miniconda3/1200px-Jupyter_logo.svg.png
EOT
fi

conda install -c conda-forge bash_kernel
python -m bash_kernel.install

echo "Jupyterlab is installed"
echo "Extend Jupyter by running 'extend jupyter.ipynb'"
exit
